version: "3"

services:
  task-service:
    container_name: task-service
    build:
      context: task-service
    depends_on:
      - postgres
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
  mail-service:
    container_name: mail-service
    build:
      context: mail-service
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8081:8081"
  postgres:
    image: postgres:bullseye
    container_name: database
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
